// swift-tools-version:5.9
// GENERATED by `dart run flutter_pear:pack` from barekit-pin.json -- DO NOT EDIT BY HAND (flutter_pear-ovt.3.5).
//
// Known SPM url: binaryTarget issues to watch for:
// - Xcode Cloud cache collision: flutter/flutter#187710
// - Cache-resolution footgun: flutter/flutter#186054
import Foundation
import PackageDescription

let bareKitURL = ProcessInfo.processInfo.environment["FLUTTER_PEAR_BAREKIT_URL"] ?? "https://github.com/andrewloable/flutter_pear/releases/download/barekit-v2.3.0/BareKit-2.3.0-ios.xcframework.zip"

let package = Package(
    name: "flutter_pear_bare",
    platforms: [.iOS(.v13)],
    products: [
        // Flutter's SPM-plugin convention: FlutterGeneratedPluginSwiftPackage looks up this product by name
        // with underscores replaced by hyphens; the TARGET below keeps the underscored name.
        .library(name: "flutter-pear-bare", targets: ["flutter_pear_bare"]),
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework")
    ],
    targets: [
        // BareKit.xcframework ships no Modules/module.modulemap -- CBareKit re-exports BareKit.h as a
        // Clang module so Swift can `import CBareKit` without a bridging header (SPM targets can't use one).
        .target(
            name: "CBareKit",
            dependencies: ["BareKit"],
            path: "Sources/CBareKit",
            publicHeadersPath: "include"
        ),
        .target(
            name: "flutter_pear_bare",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                "CBareKit",
                "AddonBareFs",
                "AddonBareInspect",
                "AddonBareOs",
                "AddonBarePipe",
                "AddonBareType",
                "AddonBareUrl",
                "AddonFsNativeExtensions",
                "AddonQuickbitNative",
                "AddonRabinNative",
                "AddonRocksdbNative",
                "AddonSimdleNative",
                "AddonSodiumNative",
                "AddonUdxNative",
            ]
        ),
        .binaryTarget(name: "BareKit", url: bareKitURL, checksum: "bb54259f54078cca69f54d868f36b3c2f72c95fcf5bca29db862f695f05a4ba7"),
        .binaryTarget(name: "AddonBareFs", path: "addons/bare-fs.4.7.3.xcframework"),
        .binaryTarget(name: "AddonBareInspect", path: "addons/bare-inspect.3.1.4.xcframework"),
        .binaryTarget(name: "AddonBareOs", path: "addons/bare-os.3.9.3.xcframework"),
        .binaryTarget(name: "AddonBarePipe", path: "addons/bare-pipe.4.2.2.xcframework"),
        .binaryTarget(name: "AddonBareType", path: "addons/bare-type.1.1.0.xcframework"),
        .binaryTarget(name: "AddonBareUrl", path: "addons/bare-url.2.4.5.xcframework"),
        .binaryTarget(name: "AddonFsNativeExtensions", path: "addons/fs-native-extensions.1.5.0.xcframework"),
        .binaryTarget(name: "AddonQuickbitNative", path: "addons/quickbit-native.2.4.8.xcframework"),
        .binaryTarget(name: "AddonRabinNative", path: "addons/rabin-native.2.0.0.xcframework"),
        .binaryTarget(name: "AddonRocksdbNative", path: "addons/rocksdb-native.3.17.1.xcframework"),
        .binaryTarget(name: "AddonSimdleNative", path: "addons/simdle-native.1.3.9.xcframework"),
        .binaryTarget(name: "AddonSodiumNative", path: "addons/sodium-native.5.1.0.xcframework"),
        .binaryTarget(name: "AddonUdxNative", path: "addons/udx-native.1.20.7.xcframework"),
    ]
)
