// swift-tools-version:5.9
// GENERATED by `dart run flutter_pear:pack` from barekit-pin.json -- DO NOT EDIT BY HAND (flutter_pear-ovt.2.4).
//
// Known SPM url: binaryTarget issues to watch for:
// - Xcode Cloud cache collision: flutter/flutter#187710
// - Cache-resolution footgun: flutter/flutter#186054
import Foundation
import PackageDescription

let bareKitURL = ProcessInfo.processInfo.environment["FLUTTER_PEAR_BAREKIT_URL"] ?? "PENDING-UPLOAD: run `dart run flutter_pear:pack --repack-barekit` (uploading enabled) to publish the repacked BareKit-2.3.0-ios.xcframework.zip and fill this in"

let package = Package(
    name: "BareKitShim",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "BareKitShim", targets: ["BareKit", "AddonBareFs", "AddonBareInspect", "AddonBareOs", "AddonBareType", "AddonBareUrl", "AddonFsNativeExtensions", "AddonQuickbitNative", "AddonRabinNative", "AddonRocksdbNative", "AddonSimdleNative", "AddonSodiumNative", "AddonUdxNative"]),
    ],
    targets: [
        .binaryTarget(name: "BareKit", url: bareKitURL, checksum: "9788ad37564523f6043422684540e290e4c3fcd33ce1bbcb8c3333820d55bd57"),
        .binaryTarget(name: "AddonBareFs", path: "addons/bare-fs.4.7.3.xcframework"),
        .binaryTarget(name: "AddonBareInspect", path: "addons/bare-inspect.3.1.4.xcframework"),
        .binaryTarget(name: "AddonBareOs", path: "addons/bare-os.3.9.3.xcframework"),
        .binaryTarget(name: "AddonBareType", path: "addons/bare-type.1.1.0.xcframework"),
        .binaryTarget(name: "AddonBareUrl", path: "addons/bare-url.2.4.5.xcframework"),
        .binaryTarget(name: "AddonFsNativeExtensions", path: "addons/fs-native-extensions.1.5.0.xcframework"),
        .binaryTarget(name: "AddonQuickbitNative", path: "addons/quickbit-native.2.4.8.xcframework"),
        .binaryTarget(name: "AddonRabinNative", path: "addons/rabin-native.2.0.0.xcframework"),
        .binaryTarget(name: "AddonRocksdbNative", path: "addons/rocksdb-native.3.17.1.xcframework"),
        .binaryTarget(name: "AddonSimdleNative", path: "addons/simdle-native.1.3.9.xcframework"),
        .binaryTarget(name: "AddonSodiumNative", path: "addons/sodium-native.5.1.0.xcframework"),
        .binaryTarget(name: "AddonUdxNative", path: "addons/udx-native.1.20.7.xcframework"),
    ]
)
